---
- name: Assign cert file paths to vars
  set_fact:
    cert_files:
      public: '/etc/ssl/certs/{{__cert_prefix_ngx__}}.public.key.pem'
      private: '/etc/ssl/private/{{__cert_prefix_ngx__}}.private.key.pem'
- name: https certs are still valid
  script: > 
    installed_certs.py
    check 
    '{{__server_name_ngx__}}'
    '{{cert_files["public"]}}', 
    '{{cert_files["private"]}}'
  args:
    executable: python3
  register: valid_certs
  changed_when: valid_certs.stdout == ""
- name: Download updated certificates
  uri:
    url: 'https://api.porkbun.com/api/json/v3/ssl/retrieve/{{__server_name_ngx__}}'
    body_format: json
    method: POST
    body:
      secretapikey: '{{__keys_ngx__["pb_secret"]}}'
      apikey: '{{__keys_ngx__["pb_api_key"]}}'
  register: fetched

- name: Replace public key
  become: true
  copy:
    dest: '{{cert_files["public"]}}'
    content: '{{fetched.json["certificatechain"].rstrip("\n")}}'
  notify: Restart nginx
- name: Replace private key
  become: true
  copy:
    dest: '{{cert_files["private"]}}'
    content: '{{fetched.json["privatekey"].rstrip("\n")}}'
  notify: Restart nginx
- name: Copy evil config
  become: true
  template:
    src: nginx_evil_template.j2
    dest: /etc/nginx/sites-enabled/nginx_evil.conf
- name: Replace web config
  become: true
  template: 
    src: nginx_template.j2
    dest: '/etc/nginx/sites-enabled/{{__conf_name_ngx__}}.conf'
  vars:
    listen: '443 ssl ipv6only=off'
  notify: Restart nginx